version: '3.7'
services:
  api:
    depends_on:
      postgres: 
          condition: service_healthy
    container_name: toro-api
    image: toroinvestimentos-backend
    build:
      context: .
      dockerfile: ToroInvestimentos.Backend.API/Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - torobackend-network
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
        - '5432:5432'
    expose:
        - "5432"
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - torobackend-network
      
networks:
  torobackend-network:
    driver: bridge
